language: C

sudo: required

before_install:
 - sudo apt-get install gfortran
 - sudo pip install numpy pandas termcolor
 - sudo apt install netcdf-bin libnetcdf-dev libnetcdff-dev
install: true

script:
 - cd VOM_Fortran; make; make check




