language: C

sudo: required

before_install:
	- sudo apt-get install gfortran

install: true

script:
	- gfortran -o model.x VOM-code/modules.f90 VOM-code/coreprog.f90 VOM-code/sample.f90 VOM-code/sce.f90 VOM-code/transpmodel.f90 VOM-code/watbal.f90 




