language: C

sudo: required

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install gfortran

install: true

script:
  - make check

after_success: 
   - echo "succes"> test.log

after_script:
   - echo "succes2"> test.log


